"""initial schema

Revision ID: 1c75097876de
Revises: 
Create Date: 2026-07-29 00:35:49.143170
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1c75097876de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('role_code', sa.String(length=20), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_idempotency_user_token')
    )
    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_user_id'), ['user_id'], unique=False)

    op.create_table('reason_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'code', name='uq_reason_kind_code')
    )
    with op.batch_alter_table('reason_masters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reason_masters_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reason_masters_kind'), ['kind'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('rough_deadline_at', sa.DateTime(), nullable=True),
    sa.Column('reply_deadline_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_orders_store_vendor_date', ['store_id', 'vendor_id', 'delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jan_code', sa.String(length=20), nullable=False),
    sa.Column('own_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('spec', sa.String(length=80), nullable=True),
    sa.Column('case_qty', sa.Integer(), nullable=False),
    sa.Column('order_unit', sa.String(length=10), nullable=False),
    sa.Column('allow_loose', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_jan_code'), ['jan_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_own_code'), ['own_code'], unique=False)
        batch_op.create_index('ix_products_vendor_active', ['vendor_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=False)

    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('rough_days_before', sa.Integer(), nullable=False),
    sa.Column('rough_time', sa.String(length=5), nullable=False),
    sa.Column('final_days_before', sa.Integer(), nullable=False),
    sa.Column('final_time', sa.String(length=5), nullable=False),
    sa.Column('reply_days_before', sa.Integer(), nullable=False),
    sa.Column('reply_time', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deadlines_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'product_id', name='uq_favorite')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_store_id'), ['store_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedup_key', name='uq_notification_dedup')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('jan_code', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('spec', sa.String(length=80), nullable=True),
    sa.Column('order_unit', sa.String(length=10), nullable=False),
    sa.Column('case_qty', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('qty_case', sa.Integer(), nullable=False),
    sa.Column('qty_loose', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('confirmed_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_order_items_order_product', ['order_id', 'product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_status'), ['status'], unique=False)

    op.create_table('product_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('vendor_product_code', sa.String(length=40), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'vendor_id', name='uq_product_vendor')
    )
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('before_case', sa.Integer(), nullable=False),
    sa.Column('before_loose', sa.Integer(), nullable=False),
    sa.Column('before_quantity', sa.Integer(), nullable=False),
    sa.Column('requested_case', sa.Integer(), nullable=False),
    sa.Column('requested_loose', sa.Integer(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('vendor_confirmed_by', sa.Integer(), nullable=True),
    sa.Column('vendor_confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_requests_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_requests_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_requests_status'), ['status'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=200), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_notification_id'), ['notification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_user_id'), ['user_id'], unique=False)

    op.create_table('order_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('qty_before', sa.Integer(), nullable=True),
    sa.Column('qty_after', sa.Integer(), nullable=True),
    sa.Column('case_before', sa.Integer(), nullable=True),
    sa.Column('case_after', sa.Integer(), nullable=True),
    sa.Column('loose_before', sa.Integer(), nullable=True),
    sa.Column('loose_after', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('is_after_deadline', sa.Boolean(), nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('vendor_confirmed_by', sa.Integer(), nullable=True),
    sa.Column('vendor_confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_histories_change_request_id'), ['change_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_histories_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_histories_order_item_id'), ['order_item_id'], unique=False)

    op.create_table('order_status_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('status_before', sa.String(length=20), nullable=True),
    sa.Column('status_after', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_status_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_status_histories_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status_histories_order_item_id'), ['order_item_id'], unique=False)

    op.create_table('vendor_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('response_type', sa.String(length=20), nullable=False),
    sa.Column('ordered_qty', sa.Integer(), nullable=True),
    sa.Column('deliverable_qty', sa.Integer(), nullable=True),
    sa.Column('shortage_qty', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('shortage_reason', sa.Text(), nullable=True),
    sa.Column('next_available_date', sa.Date(), nullable=True),
    sa.Column('has_substitute', sa.Boolean(), nullable=False),
    sa.Column('sub_product_name', sa.String(length=150), nullable=True),
    sa.Column('sub_jan_code', sa.String(length=20), nullable=True),
    sa.Column('sub_spec', sa.String(length=80), nullable=True),
    sa.Column('sub_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sub_deliverable_qty', sa.Integer(), nullable=True),
    sa.Column('sub_delivery_date', sa.Date(), nullable=True),
    sa.Column('sub_comment', sa.Text(), nullable=True),
    sa.Column('sub_approved_by', sa.Integer(), nullable=True),
    sa.Column('sub_approved_at', sa.DateTime(), nullable=True),
    sa.Column('sub_rejected_by', sa.Integer(), nullable=True),
    sa.Column('sub_rejected_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('responder_id', sa.Integer(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_responses_is_latest'), ['is_latest'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_responses_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_responses_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_responses_response_type'), ['response_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_responses_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_responses_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_responses_response_type'))
        batch_op.drop_index(batch_op.f('ix_vendor_responses_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_responses_order_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_responses_is_latest'))

    op.drop_table('vendor_responses')
    with op.batch_alter_table('order_status_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_histories_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_order_status_histories_order_id'))

    op.drop_table('order_status_histories')
    with op.batch_alter_table('order_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_histories_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_order_histories_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_histories_change_request_id'))

    op.drop_table('order_histories')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_notification_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_dedup_key'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_requests_status'))
        batch_op.drop_index(batch_op.f('ix_change_requests_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_change_requests_order_id'))

    op.drop_table('change_requests')
    op.drop_table('product_vendors')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_status'))
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index('ix_order_items_order_product')
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_deleted_at'))

    op.drop_table('order_items')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_order_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_store_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadlines_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_deadlines_scope'))
        batch_op.drop_index(batch_op.f('ix_deadlines_product_id'))
        batch_op.drop_index(batch_op.f('ix_deadlines_delivery_date'))
        batch_op.drop_index(batch_op.f('ix_deadlines_deleted_at'))

    op.drop_table('deadlines')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_vendor_id'))
        batch_op.drop_index('ix_products_vendor_active')
        batch_op.drop_index(batch_op.f('ix_products_own_code'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_jan_code'))
        batch_op.drop_index(batch_op.f('ix_products_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_vendor_id'))
        batch_op.drop_index('ix_orders_store_vendor_date')
        batch_op.drop_index(batch_op.f('ix_orders_store_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_orders_delivery_date'))
        batch_op.drop_index(batch_op.f('ix_orders_deleted_at'))

    op.drop_table('orders')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_deleted_at'))

    op.drop_table('vendors')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_deleted_at'))

    op.drop_table('stores')
    op.drop_table('roles')
    with op.batch_alter_table('reason_masters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reason_masters_kind'))
        batch_op.drop_index(batch_op.f('ix_reason_masters_deleted_at'))

    op.drop_table('reason_masters')
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_logs_email'))
        batch_op.drop_index(batch_op.f('ix_login_logs_created_at'))

    op.drop_table('login_logs')
    op.drop_table('idempotency_keys')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_store_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
